### PR TITLE
Allow `browscap-js-cache` backend to return a `Promise`

### PR DESCRIPTION
**Pull request by ntninja**
Title says it all: This patch transparently allows the cache backend to return a promise instead of a JSON result if it doesn't yet have any result available. This important in Web contexts (such as web-pages, or, in my case, browser extensions) that don't have the ability to do synchronous I/O when reading files. And probably could also be useful in Node.JS (asynchronous I/O is the prefered way there too!).

As documented in the respective comments, the code replaces the Node.JS default `Promise` implementation with `SynchronousPromise` to allow for results to be propagated synchronously to the caller if no actual asynchronous operations where involved. Without this it would not be possible to unpack the final value synchonously when using the default `browscap-js-cache` backend and this would break backward compatibility with existing dependants as well as the current unit tests.

### CODE REVIEW

**Comment by mimmi20** [comment]
The build is failing on node.js below version 6. Does `synchronous-promise` require node 6?

**Comment by ntninja** [comment]
I tested this on an Ubuntu 16.04LTS VM with NodeJS v4.2.6: It turns out the Array-unpack syntax is not supported on this version.
Since the Travis build output is pretty unhelpful I don't think I can test with versions below this however.

**Comment by ntninja** [comment]
The current build error is with NodeJS 0.* and looks like an incompatibility in the `mocha` test runner itself:

```
/home/travis/build/mimmi20/browscap-js/node_modules/mocha/node_modules/supports-color/index.js:2
const os = require('os');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/travis/build/mimmi20/browscap-js/node_modules/mocha/lib/reporters/base.js:11:46)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by mimmi20** [comment]
Please add the following changes to your PR:
- remove all versions of node.js below 4 in `.travis.yml`
- set the required node.js version to 4 in `package.json`

**Comment by mimmi20** [comment]
mocha has dropped the support for node.js versions below 4

**Comment by ntninja** [comment]
> mocha has dropped the support for node.js versions below 4

Thank goodness 😉 

> Please add the following changes to your PR:

Done

**Comment by ntninja** [comment]
… and the build passed!

**Pull request merged**
