### PR TITLE
Switched to npm json cache

### PR DESCRIPTION
**Pull request by funtaps**
Hello, I propose to switch to npm, and get rid of postinstall scripts.

Advantages:
1. More obvious updates
2. Can be cached at local npm registries (no need to download from network every time).
3. Works with yarn (https://github.com/yarnpkg/yarn)

I created npm package https://www.npmjs.com/package/browscap-json-cache-files for testing purposes.

### CODE REVIEW

**Comment by mimmi20** [comment]
The cache were part of this repo once, but I could not publish anything at the end. I had timeouts during the publish process because of the size of the project.
The browscap project as the source of the cache files is changing its versioning system at the moment. I will wait until this is finished and test afterwards publishing the cache files.

**Comment by mimmi20** [comment]
@funtaps Please add me to the project you created. I would like to publish a new version.

**Comment by funtaps** [comment]
Done, sorry for a delay

**Comment by mimmi20** [comment]
Thanks

**Pull request merged**
